### PR TITLE
Quoted argument escaping fix & support for logging parameters

### PR DESCRIPTION
**Pull request by davidqhogan**

### CODE REVIEW

**Comment by sjPlot** [comment]
Since I fixed the second issue already, I would like to merge the first file only - but how to do this?

**Comment by davidqhogan** [comment]
Thanks for the formatting fixes, i'll keep those in mind when submitting further patches.

Looking at your commit - I don't think you did fix the escaping issue, as

`if (character != '"' && character == '\\') {` needs to be changed to `if (character != '"' && character != '\\') {` (I had incompletely refactored it from an OR based expression)

I'm still new to git and github (long time svn user) - but I think if I pull your changes, merge locally and commit to my branch, this pull request will be updated. Will try that now

**Comment by davidqhogan** [comment]
Ok that worked, this pull request is now updated for your review.

I believe that initialising the StringBuilder with an instance wastes an object allocation, as a new StringBuilder is created at the beginning of each new token - therefore I reverted the change you made to initialise it. If you prefer I can update it, but as far as I can tell there is no case in which that object would get used.

**Comment by sjPlot** [comment]
> I believe that initialising the StringBuilder with an instance wastes an object allocation, as a new StringBuilder is created at the beginning of each new token - therefore I reverted the change you made to initialise it.

I did this change because NetBeans gave a warning about this, saying that `token` might not be initialized on first occurrence. My experience with the NetBeans Code Diagnostics is quite positive, so mostly I follow the suggestion given by the IDE.

**Comment by sjPlot** [comment]
I have uploaded binaries, so you may test the changes as well...
http://sourceforge.net/projects/relaunch64/files/devel/

**Comment by davidqhogan** [comment]
Fair enough - I am used to Eclipse rather than NetBeans and therefore hadn't noticed the warnings.

If it was previously possible to dereference that null pointer, my worry now is that this change hides the parsing bug and will produce incorrect output which will be quite hard to debug for the user. Of course - this is much better than a crash caused by a NullPointerException! Another worry is that same NPE (if possible) could occur after the token is reset to null when the state returns to BETWEEN_TOKENS.

What do you think about instead adding a couple of null checks that remove the NetBeans warnings, log an error and return something that wont execute, something like:

```Java
if (token == null) {
    ConstantsR64.r64logger.log(Level.SEVERE, "Failed to parse: {0}", command);
    return new String[]{"PARSE ERROR"};
}
```

If you like this idea I would be happy to submit a pull request. The block is only needed in two places.

Regarding binaries - I've actually been testing it by building and launching from NetBeans on OS X (manually added the missing libs). If I get ant in my path and run that ant file in the project root, will that result in an .app being built ?

**Comment by sjPlot** [comment]
Yes, feel free to submit another pull request with your suggestions.

According to the libraries: a compiled version of the jEdit TextArea should be available here: https://github.com/sjPlot/Relaunch64/issues/8 (if not, tell me and I'll upload it).

According to the ANT-script (I'm not much experienced with that, I just know a little Java coding and tried to get the rest running somehow...), I first clean and run the project:

r641

and then I first run the `package-for-store` script from the `build.xml` file, and then the first `Bundle OS X.app` script to create an .app file (just for convenience and distribution).

r64shot2

**Comment by davidqhogan** [comment]
Thanks and thanks! I ended up finding a better option than my null check suggestion, pull request created.

**Pull request merged**
